### DISCUSSION TITLE
Beta Testing & Debugging

### DISCUSSION THREAD

**Discussion by vmsman** [AnthonyGress/lab-dash#91] [General]
This is a discussion for beta testing, new features, and bugs

**Comment by AnthonyGress** [comment]
Yes I could make it run on port 80

**Comment by AnthonyGress** [comment]
Couldn't you just map the host port 80 to the apps port 2022 in the docker-compose file. I don't see why any change in the application is required.

```
---
services:
  lab-dash:
      container_name: lab-dash
      image: ghcr.io/anthonygress/lab-dash:latest
      privileged: true
      network_mode: host # for monitoring network usage stats
      ports:
        - 80:2022 # Change this to 80:2022, mapping host port 80 to the docker containers 2022
      environment:
        - SECRET=YOUR_SECRET_KEY # any random string for used for encryption.
        # You can run `openssl rand -base64 32` to generate a key
      volumes:
        - /sys:/sys:ro
        - /docker/lab-dash/config:/config
        - /docker/lab-dash/uploads:/app/public/uploads
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
      labels:
        - "com.centurylinklabs.watchtower.enable=true"

```
